### ISSUE TITLE
Will the saga continue?

### ISSUE THREAD

**Issue by shapedthought** [programatik29/axum-tutorial#3]
Just wondered if you'll be continuing with this?

**Comment by programatik29** [comment]
Yes. I will restructure the tutorial, make it like rust [mdbook](https://github.com/rust-lang/mdBook) style and add much more content targeting beginners, intermediate and library developers.

**Comment by shapedthought** [comment]
Great, I'll keep any eye out for it.

**Comment by erlangparasu** [comment]
Any updates? 😃

**Comment by programatik29** [comment]
> Any updates? smiley

@erlangparasu I delayed it a bit because of life stuff. But I am back on track (hopefully).

New tutorial which will use mdbook roughly looks like this(https://github.com/programatik29/axum-tutorial/tree/new).

**Comment by programatik29** [comment]
Done. New chapters are coming soon.
